### ISSUE TITLE
XDITA samples need LwDITA DTD declaration

### ISSUE THREAD

**Issue by carlosevia** [DITAWriter/LwDITA_Code_Samples#2]
Files in the XDITA folder use the DITA DTD declaration: <!DOCTYPE topic
PUBLIC "-//OASIS//DTD DITA Topic//EN" "topic.dtd">
The LwDITA DTD declaration for XDITA should be: 
<!DOCTYPE topic PUBLIC "-//OASIS//DTD LIGHTWEIGHT DITA Topic//EN" "lw-topic.dtd">

**Comment by DITAWriter** [comment]
Fixed!
